### ISSUE TITLE
MicroTrades - buy orders duplication and random failures

### ISSUE THREAD

**Issue by Haidy777** [Haidy777/bit-trader#21]
sometimes the microtrades strategie executes an order twice or exits unexpectedly:

```
Unhandled rejection Error: Kraken API returned error: API:Invalid nonce
    at Request.<anonymous> (/home/phprojek/bit-trader/node_modules/kraken-api/kraken.js:180:21)
    at Request._callback (/home/phprojek/bit-trader/node_modules/lodash/lodash.js:10067:25)
    at Request.requestRetryReply [as reply] (/home/phprojek/bit-trader/node_modules/requestretry/index.js:105:19)
    at Request.<anonymous> (/home/phprojek/bit-trader/node_modules/requestretry/index.js:133:10)
    at Request.self.callback (/home/phprojek/bit-trader/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/phprojek/bit-trader/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/phprojek/bit-trader/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
```

**Comment by ThePatzi** [comment]
The best solution to prevent wrong nounce would be to "outsource" the sender part into an own process. The sender process would be responsible for generating valid nounces, sending the request and to pass the result back to the other processes.
